always_for_in = true
always_use_return = true
margin = 120
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
short_to_long_function_def = false
whitespace_typedefs = true
whitespace_in_kwargs = false
whitespace_ops_in_indices = true