---
title: "Modeling long-term energy transition pathways: Algorithmic approaches and their properties"
subtitle: test
date: 02.07.2024
format:
  beamer:
    theme: CambridgeUS
    aspectratio: 169
author: "John Doe s"
institute: asd
callout-appearance: simple
---

# Transition Pathways

## Snapshot Models

::: {.callout-note}
### Definition

- operate on consecutive _snapshots_ ("= time steps") of a system
- for each, all input data can be specified
- often make use of (multi-) hourly snapshots
- often span a single, full year
:::

::: {.callout-tip}
### Properties
- are "easy" to describe mathematically
- provide insights into the energy system for individual years
- lack the ability to depict dynamics in investment strategies throughout a transition period
:::

## Transition / Pathway Models

::: {.callout-note}
### Definition

- can be seen as extension to snapshot models
- represent the entire transition pathway to a long term target
:::

::: {.callout-tip}
### Properties
- can be "hard" to describe mathematically
- provide insights into the energy system over a period of many years
- quickly become computationally intractable
- are not fully supported by many tools
:::
